### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Giyuubutdiff** [YUNG-GANG/YUNGs-API#11]
when i put yungs api forge 12 in my mods and launch tlauncher it crashes

**Comment by TelepathicGrunt** [comment]
Tlauncher is a piracy software to play minecraft without paying for it. Most mod developers will not provide support for people using tlauncher because that launcher is against Mojang's terms of service and isn't legal. You should switch to using GDLauncher, MultiMC, or CurseForge's launcher for playing with mods as those are legal and safer to use. And more mod developers will be willing to help you out.

If the game still crashes using one of these other launchers, please provider the latest.log file as it will say why the game crashed and we can work from there.

**Comment by yungnickyoung** [comment]
I don't support pirated content. Please open another issue if the problem persists with a legitimate Minecraft launcher.
